//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public long Idfile { get; set; }
        public string idproject { get; set; }
        public string srcimagetarget { get; set; }
        public string newimagetarget { get; set; }
    
        public virtual file file1 { get; set; }
        public virtual file file2 { get; set; }
    }
}
