//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int idproject { get; set; }
        public Nullable<int> iduser { get; set; }
    
        public virtual project project1 { get; set; }
        public virtual project project2 { get; set; }
    }
}
